// Generates src/styles/tokens.css from tokens.json. Do not edit tokens.css by hand.
import { readFileSync, writeFileSync } from 'node:fs';
import { basename } from 'node:path';
import { fileURLToPath } from 'node:url';

// A reference value such as "{blue}" becomes var(--blue).
function cssValue(v) {
  const ref = v.match(/^\{([a-z0-9-]+)\}$/);
  return ref ? `var(--${ref[1]})` : v;
}

function themed(v, theme) {
  return cssValue(typeof v === 'string' ? v : v[theme]);
}

function decls(tokens, theme) {
  return tokens.map(({ name, value }) => `  --${name}: ${themed(value, theme)};`);
}

export function generate(tokens) {
  const faces = tokens.type.fonts.map((f) =>
    [
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  src: url('/fonts/${basename(f.file)}') format('woff2');`,
      `  font-weight: ${f.weight};`,
      '  font-style: normal;',
      '  font-display: swap;',
      '}',
    ].join('\n'),
  );
  const families = Object.entries(tokens.type.families).map(([k, v]) => `  --font-${k}: ${v};`);
  const root = [
    ':root {',
    '  color-scheme: light dark;',
    ...decls(tokens.color.tokens, 'light'),
    ...decls(tokens.spacing.tokens, 'light'),
    ...decls(tokens.radius.tokens, 'light'),
    ...decls(tokens.shadow.tokens, 'light'),
    ...families,
    '}',
  ].join('\n');
  const dark = [
    '@media (prefers-color-scheme: dark) {',
    '  :root {',
    ...decls(tokens.color.tokens, 'dark').map((l) => `  ${l}`),
    ...decls(tokens.shadow.tokens, 'dark').map((l) => `  ${l}`),
    '  }',
    '}',
  ].join('\n');
  return `/* Generated by scripts/gen-tokens.mjs from tokens.json. Do not edit. */\n\n${[...faces, root, dark].join('\n\n')}\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const tokens = JSON.parse(readFileSync(new URL('../tokens.json', import.meta.url), 'utf8'));
  writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), generate(tokens));
}
